/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8fafc',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f8fafc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#45464d',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        outline: '#76777d',
        'outline-variant': '#d1d5db',
        'surface-tint': '#0f172a',
        primary: '#0f172a',
        'on-primary': '#ffffff',
        'primary-container': '#131b2e',
        'on-primary-container': '#c9ccd6',
        'inverse-primary': '#bec6e0',
        secondary: '#10b981',
        'on-secondary': '#ffffff',
        'secondary-container': '#d1fae5',
        'on-secondary-container': '#047857',
        tertiary: '#3b82f6',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#dbeafe',
        'on-tertiary-container': '#1d4ed8',
        warning: '#f59e0b',
        'on-warning': '#78350f',
        'warning-container': '#fef3c7',
        'on-warning-container': '#92400e',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed': '#001a42',
        'on-tertiary-fixed-variant': '#004395',
        background: '#f8fafc',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
        'focus-ring': '#3b82f6',
        
        // Brand details from DESIGN.md
        'brand-deep-slate': '#0F172A',
        'brand-emerald-green': '#10B981',
        'brand-blue': '#3B82F6',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        xs: '0.25rem',
        sm: '0.375rem',
        DEFAULT: '0.375rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        full: '9999px',
      },
      spacing: {
        unit: '4px',
        'container-max': '1440px',
        'sidebar-width': '260px',
        gutter: '24px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      width: {
        'sidebar-width': '260px',
      }
    },
  },
  plugins: [],
}
